#!/bin/bash
sudo apt update
sudo apt install -y metasploit-framework
sudo apt install -y nmap
sudo apt install -y tshark
sudo apt install -y gobuster
sudo apt install -y sqlmap
sudo apt install -y net-tools
sudo apt install -y whatweb
sudo apt install -y dnsutils
