#!/bin/bash
sudo apt update
sudo apt install metasploit-framework
sudo apt install nmap
sudo apt install tshark
sudo apt install gobuster
sudo apt install sqlmap
sudo apt install net-tools
sudo apt install whatweb
